[package]
name = "fact_base"
version = "0.1.0"
authors = ["Yirmandias <turi@etud.insa-toulouse.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aries_model = {git = "https://github.com/arthur-bit-monnot/aries/"}
aries_planning = {git = "https://github.com/arthur-bit-monnot/aries/"}
aries_utils = {git = "https://github.com/arthur-bit-monnot/aries/"}
aries_collections = {git = "https://github.com/arthur-bit-monnot/aries/"}
anyhow = "1.0.38"
structopt = { version = "0.3", default-features = false }