[workspace]

members = [
    "apps", "lisp", "godot-simulation-client", "modules", "acting", "tests"
]

[profile.release]
debug = true                # Debug symbols for benchmarking
opt-level = 3
lto = "thin"
codegen-units = 8
panic = "abort"
