[workspace]

members = [
    "apps", "lisp", "godot-simulation-client", "modules", "acting"
]

[profile.dev]
opt-level = 2               # Use slightly better optimizations.


[profile.release]
debug = true                # Debug symbols for benchmarking
opt-level = 3
lto = "thin"
codegen-units = 8
panic = "abort"
incremental = true