[workspace]


members = [
    "scheme/core",
    "scheme/macros",
    "scheme/utils",
    "scheme/structs",
    "scheme/repl",
    "scheme/apps",
    "scheme/modules",
    "scheme/language",
    "resources/playground",
    "rae/apps",
    "rae/core",
    "rae/language",
    "rae/log",
    "rae/planning",
    "rae/structs",
    "gobotsim",
    "benchmark",
    "rae/flow_graph",
]

exclude = ["aries"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



