[package]
name = "sompas-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ompas-utils = {path = "../../utils" }
sompas-structs = {path = "../structs"}
sompas-language = {path = "../language"}
sompas-macros = {path = "../macros"}
ompas-middleware = {path = "../../middleware"}
aries_planning = {path = "../../aries/planning/planning"}
async-trait = {workspace = true}
async-recursion = {workspace = true}
anyhow = {workspace = true}
tokio = {workspace = true}
im = {workspace = true}
lazy_static = {workspace = true}
macro_rules_attribute = {workspace = true}
function_name = {workspace = true}
futures = {workspace = true}
