[book]
authors = ["Jérémy Turi"]
language = "en"
multilingual = false
src = "src"
title = "OMPAS Documentation"

[output.html]
mathjax-support = true

[preprocessor.bib]
bibliography = "ompas-doc.bib"