[package]
name = "sompas-repl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ompas-utils = {path = "../../utils" }
ompas-middleware = {path = "../../middleware"}

sompas-core = {path = "../core"}
sompas-structs = {path = "../structs"}
sompas-language = {path = "../language"}

im = { workspace =true }
tokio =  { workspace =true }
chrono =  { workspace =true }
map-macro =  { workspace =true }
rustyline = {workspace = true}

