[package]
name = "sompas-structs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sompas-language = {path = "../language"}

ompas-middleware = {path = "../../middleware"}

im = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
anyhow = { workspace = true }
macro_rules_attribute = { workspace = true }
function_name = { workspace = true }

serde = { version = "1.0", features = ["derive"]}
num-traits = "0.2.14"
syn = "1.0"
