[package]
name = "sompas-structs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sompas-language = {path = "../language"}
im = "15.0.0"
serde = { version = "1.0", features = ["derive"]}
tokio = { version = "1.17.0", features = ["full", "time"] }
futures = "0.3.17"
anyhow = "1.0.56"
num-traits = "0.2.14"
macro_rules_attribute = "0.0.2"
function_name = "0.2.0"
syn = "1.0"
ompas-middleware = {path = "../../middleware"}