[package]
name = "sompas-modules"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ompas-utils = {path = "../../utils" }
ompas-middleware = {path = "../../middleware"}

sompas-structs = {path = "../structs"}
sompas-core = {path = "../core"}
sompas-language = {path = "../language"}
sompas-macros = {path = "../macros"}

aries = {path = "../../aries/solver"}

im = {workspace = true}
tokio = {workspace = true}
rand = {workspace = true}
macro_rules_attribute = {workspace = true}
futures = {workspace = true}
chrono = {workspace = true}

